# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.6.22/c2cciutils/schema.json

publish:
  docker:
    dispatch: {}
    images:
      - name: camptocamp/tilecloud-chain
  pypi:
    versions:
      - version_tag
checks:
  codespell: false
