# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.1.41/c2cciutils/schema.json

checks:
  black: false
  isort: false
  codespell: false
  versions: false
  required_workflows: false
  dependabot_config: false
  prospector_config: false
  setup: false
